-- ============================================================
-- Iki Anti-Theft Tool
-- Migration 002: Error Logs
-- ============================================================

create table if not exists public.error_logs (
    id bigint generated by default as identity primary key,

    device_id text not null,

    created_at timestamptz not null default now(),

    level text not null default 'ERROR'
        check (level in ('INFO', 'WARNING', 'ERROR')),

    source text not null,

    error_code text not null,

    message text not null
);

-- Row Level Security aktivieren
alter table public.error_logs enable row level security;

-- Index für Geräte-/Zeitabfragen
create index if not exists idx_error_logs_device_created
    on public.error_logs (device_id, created_at desc);

-- Index für Fehlerquelle
create index if not exists idx_error_logs_source
    on public.error_logs (source);

-- Index für Schweregrad
create index if not exists idx_error_logs_level
    on public.error_logs (level);